name: Customizable
on:
  push:
  workflow_dispatch:
    inputs:
      client_name:
        description: "Client"
        required: false
        default: "main"
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  #   inputs:
  #     clients: [main, demo]
jobs:
  configure_matrix:
    name: Configure CI matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Get pull request commit message from SHA
        if: ${{github.event_name == 'pull_request'}}
        shell: bash
        run: |
          echo "sha from GITHUB_SHA: ${GITHUB_SHA}"
          echo "event sha: ${{github.event.sha }}"
          echo git log --format=%B -n 1 $GITHUB_SHA
          echo "X_PR_COMMIT=$(git log --format=%B -n 1 ${GITHUB_SHA})" >> $GITHUB_ENV

      - name: Get branch name (merge)
        if: ${{github.event_name != 'pull_request'}}
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: ${{github.event_name == 'pull_request'}}
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Debug
        run: echo ${{ env.BRANCH_NAME }}

      - id: set-head-commit
        name: set the head commit message as env
        run: |
          echo "COMMITMSG=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
      - run: echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          X_ON_MAIN_BRANCH: ${{ contains(github.event.ref, 'refs/heads/main') }}
          X_REQUESTED_ALL_CLIENTS: ${{ contains(github.event.head_commit.message, 'ci full') }}
      - id: set-matrix
        name: set matrix
        # env:
        #   COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          echo "GITHUB_HEAD_REF is ${GITHUB_HEAD_REF} hello"
          echo "interpolate '${{ github.event.head_commit.message }}'"
          echo "interpolate contains ${{ contains(github.event.head_commit.message, 'ci full') }}"
          echo "requested_all_clients=${{ contains(github.event.head_commit.message, 'ci full') }}"

          echo "Hello ${{ github.event.inputs.client_name }}!"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})"
          echo "branchreffrominterp=${{ github.event.ref }}"
          echo "on_main=${{ contains(github.event.ref, 'refs/heads/main') }}"
          echo "on_main=${{ startsWith(github.event.ref, 'refs/heads/main') }}"
          echo "on_main=${{ github.event.ref == 'refs/heads/main' }}"
          echo "COMMIT_MESSAGE: ${COMMIT_MESSAGE}"
          echo "COMMIT_MESSAGE altt: ${{env.commitmsg}} try again"

          if [ "$on_main" == "true"  || "$requested_all_clients" == "true" ]; then
              echo "GITHUB_HEAD_REF is NOT blank '${GITHUB_HEAD_REF}' or requested_all_clients: ${requested_all_clients} "
              if [ "$requested_all_clients" == "true" ]; then
                echo "::notice::Commit message included 'ci full' so setting CI matrix to all clients"
              fi;

              if [ "$on_main" == "true" ]; then
                echo "::notice::Running on master branch so setting CI matrix to all clients"
              fi;
              echo "::set-output name=matrix::[\"main\",\"demo\"]"
          else
              echo "GITHUB_HEAD_REF is not null"
              echo "GITHUB_HEAD_REF is ${GITHUB_HEAD_REF} (so only running on single client)"
              echo "::notice::Running on a branch so only running tests for the 'main' client"
              echo "::set-output name=matrix::[\"main\"]"
          fi

  test:
    needs: configure_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client: ${{fromJson(needs.configure_matrix.outputs.matrix)}}
      fail-fast: false
    steps:
      - run: echo "Output ${{ needs.configure_matrix.outputs.matrix }}"
      - run: echo "Output ${{ fromJson(needs.configure_matrix.outputs.matrix) }}"
      - name: Last step failed
        run: echo
        if: ${{ failure() }}
      - run: echo "🧖‍♀️ The job is running for client ${{ matrix.client }}."
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "❤️ Commit is for [ci full]"
        if: "contains(github.event.head_commit.message, '[ci full]')"
      - run: echo "💚 Commit is not for [ci full]"
        if: "!contains(github.event.head_commit.message, '[ci full]')"
      - name: Last step failed
        run: echo
        if: ${{ failure() }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
